_schema: _schema
source: /
paths:
  uploads: public/static/uploads
  static: public/static
collections_config:
  pages:
    path: /src/content/pages
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/Chicago
