_schema: _schema
source: /
paths:
  uploads: public/static/uploads
  static: public/static
collections_config:
  pages:
    path: /src/content/pages
    name: Pages
    icon: wysiwyg
    url: /[slug]/
    disable_url: false
    description: ''
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
      content:
        allow_custom_markup: false
        remove_custom_markup: true
        blockquote: true
        bold: true
        bulletedlist: true
        center:
        code:
        copyformatting:
        embed:
        expandable:
        format:
        height:
        horizontalrule:
        image:
        image_size_attributes: true
        indent:
        italic:
        justify:
        left:
        link:
        mime_type:
        numberedlist:
        outdent:
        paths:
        redo:
        removeformat:
        resize_style:
        right:
        snippet:
        strike:
        styles:
        subscript:
        superscript:
        table:
        underline:
        undo: false
        width:
      image:
        expandable:
        height:
        image_size_attributes: true
        mime_type:
        paths:
        resize_style:
        width:
      link:
        paths:
    _enabled_editors:
      - visual
    _inputs:
      content:
        type: markdown
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  content:
    type: markdown
    options:
      bold: true
      italics: true
      underline: true
    cascade: true
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: America/Chicago
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
